import { RiRefreshLine } from "@remixicon/react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { MemoryDocument, MemoryDocumentId } from "../../bindings";
import { commandError } from "../../lib/errors";
import { MarkdownContent } from "../chat/MarkdownContent";
import { memoryApi } from "./memoryApi";

const documents: Array<{ id: MemoryDocumentId; name: string }> = [
  { id: "summary", name: "memory_summary.md" },
  { id: "handbook", name: "MEMORY.md" },
];

function formatBytes(size: number): string {
  if (size < 1024) return `${size} B`;
  return `${(size / 1024).toFixed(size < 10 * 1024 ? 1 : 0)} KB`;
}

export function MemorySettings() {
  const [selected, setSelected] = useState<MemoryDocumentId>("summary");
  const [document, setDocument] = useState<MemoryDocument | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<ReturnType<typeof commandError> | null>(
    null,
  );
  const request = useRef(0);

  const load = useCallback(async (id: MemoryDocumentId) => {
    const current = ++request.current;
    setLoading(true);
    setError(null);
    try {
      const next = await memoryApi.read(id);
      if (request.current === current) setDocument(next);
    } catch (failure) {
      if (request.current === current) {
        setDocument(null);
        setError(commandError(failure));
      }
    } finally {
      if (request.current === current) setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load(selected);
    return () => {
      request.current += 1;
    };
  }, [load, selected]);

  const selectedName = documents.find(({ id }) => id === selected)!.name;
  return (
    <section className="memory-settings">
      <div className="memory-heading">
        <div>
          <h3>Memory</h3>
          <p className="settings-description">
            Read the global documents generated by Pi Memory.
          </p>
        </div>
        <button
          className="memory-refresh"
          type="button"
          aria-label="Refresh memory document"
          disabled={loading}
          onClick={() => void load(selected)}
        >
          <RiRefreshLine className={loading ? "spin" : ""} size={15} />
          Refresh
        </button>
      </div>
      <div className="memory-tabs" aria-label="Memory documents">
        {documents.map((item) => (
          <button
            key={item.id}
            type="button"
            aria-pressed={selected === item.id}
            className={selected === item.id ? "active" : ""}
            onClick={() => setSelected(item.id)}
          >
            {item.name}
          </button>
        ))}
      </div>
      {loading && (
        <div className="settings-empty" role="status">
          Loading {selectedName}…
        </div>
      )}
      {!loading && error?.code === "NOT_FOUND" && (
        <div className="settings-empty">
          {selectedName} has not been generated yet.
        </div>
      )}
      {!loading && error && error.code !== "NOT_FOUND" && (
        <div className="dialog-error" role="alert">
          {error.message}
        </div>
      )}
      {!loading && document && (
        <div className="memory-document">
          <div className="memory-document-meta">
            <b>{document.name}</b>
            <span>{formatBytes(document.size)}</span>
            <span>{new Date(document.updatedAt).toLocaleString()}</span>
          </div>
          {document.content ? (
            <div className="memory-document-content">
              <MarkdownContent content={document.content} />
            </div>
          ) : (
            <div className="settings-empty">{document.name} is empty.</div>
          )}
        </div>
      )}
    </section>
  );
}
