import { useCallback, useEffect, useRef, useState } from "react";
import type {
  MemoryConfig,
  MemoryDocument,
  MemoryDocumentId,
  MemoryReasoningEffort,
} from "../../bindings";
import { commandError } from "../../lib/errors";
import { MarkdownContent } from "../chat/MarkdownContent";
import { memoryApi } from "./memoryApi";

const documents: Array<{ id: MemoryDocumentId; name: string }> = [
  { id: "summary", name: "memory_summary.md" },
  { id: "handbook", name: "MEMORY.md" },
];
const reasoningEfforts: MemoryReasoningEffort[] = [
  "off",
  "minimal",
  "low",
  "medium",
  "high",
  "xhigh",
  "max",
];

function formatBytes(size: number): string {
  if (size < 1024) return `${size} B`;
  return `${(size / 1024).toFixed(size < 10 * 1024 ? 1 : 0)} KB`;
}

function splitModel(
  value: string,
): Pick<MemoryConfig, "provider" | "modelId"> | null {
  const separator = value.indexOf("/");
  if (separator <= 0 || separator === value.length - 1) return null;
  return {
    provider: value.slice(0, separator),
    modelId: value.slice(separator + 1),
  };
}

export function MemorySettings() {
  const [selected, setSelected] = useState<MemoryDocumentId>("summary");
  const [document, setDocument] = useState<MemoryDocument | null>(null);
  const [documentLoading, setDocumentLoading] = useState(true);
  const [documentError, setDocumentError] = useState<ReturnType<
    typeof commandError
  > | null>(null);
  const [model, setModel] = useState("");
  const [reasoningEffort, setReasoningEffort] =
    useState<MemoryReasoningEffort>("low");
  const [persistedConfig, setPersistedConfig] = useState<MemoryConfig | null>(
    null,
  );
  const [configLoading, setConfigLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [configError, setConfigError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const request = useRef(0);

  const loadDocument = useCallback(async (id: MemoryDocumentId) => {
    const current = ++request.current;
    setDocumentLoading(true);
    setDocumentError(null);
    try {
      const next = await memoryApi.read(id);
      if (request.current === current) setDocument(next);
    } catch (failure) {
      if (request.current === current) {
        setDocument(null);
        setDocumentError(commandError(failure));
      }
    } finally {
      if (request.current === current) setDocumentLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadDocument(selected);
    return () => {
      request.current += 1;
    };
  }, [loadDocument, selected]);

  useEffect(() => {
    let disposed = false;
    memoryApi.getConfig().then(
      (config) => {
        if (disposed) return;
        setModel(`${config.provider}/${config.modelId}`);
        setReasoningEffort(config.reasoningEffort);
        setPersistedConfig(config);
        setConfigLoading(false);
      },
      (failure) => {
        if (disposed) return;
        setConfigError(commandError(failure).message);
        setConfigLoading(false);
      },
    );
    return () => {
      disposed = true;
    };
  }, []);

  const saveConfig = async () => {
    const parsed = splitModel(model);
    if (!parsed) {
      setConfigError("Use a full provider/model identifier.");
      return;
    }
    setSaving(true);
    setSaved(false);
    setConfigError(null);
    try {
      const config = await memoryApi.setConfig({ ...parsed, reasoningEffort });
      setModel(`${config.provider}/${config.modelId}`);
      setReasoningEffort(config.reasoningEffort);
      setPersistedConfig(config);
      setSaved(true);
    } catch (failure) {
      if (persistedConfig) {
        setModel(`${persistedConfig.provider}/${persistedConfig.modelId}`);
        setReasoningEffort(persistedConfig.reasoningEffort);
      }
      setConfigError(commandError(failure).message);
    } finally {
      setSaving(false);
    }
  };

  const selectedName = documents.find(({ id }) => id === selected)!.name;
  return (
    <section className="memory-settings">
      <div className="memory-heading">
        <div>
          <h3>Memory</h3>
          <p className="settings-description">
            Configure extraction and read the global documents generated by Pi
            Memory.
          </p>
        </div>
      </div>
      <div className="memory-config">
        <div className="memory-config-fields">
          <label>
            <span>Memory Model</span>
            <input
              aria-label="Memory Model"
              value={model}
              disabled={configLoading || saving}
              placeholder="provider/model"
              onChange={(event) => {
                setModel(event.target.value);
                setSaved(false);
              }}
            />
          </label>
          <label>
            <span>Reasoning Effort</span>
            <select
              aria-label="Reasoning Effort"
              value={reasoningEffort}
              disabled={configLoading || saving}
              onChange={(event) => {
                setReasoningEffort(event.target.value as MemoryReasoningEffort);
                setSaved(false);
              }}
            >
              {reasoningEfforts.map((effort) => (
                <option key={effort} value={effort}>
                  {effort}
                </option>
              ))}
            </select>
          </label>
        </div>
        <small>
          Controls Phase 1 extraction. Restart SpireCode after saving.
        </small>
        {configError && (
          <div className="dialog-error" role="alert">
            {configError}
          </div>
        )}
        {saved && (
          <div className="memory-config-saved">
            Restart SpireCode to apply these changes.
          </div>
        )}
        <div className="dialog-actions memory-config-actions">
          <button
            className="primary"
            type="button"
            disabled={configLoading || saving}
            aria-label="Save Memory configuration"
            onClick={() => void saveConfig()}
          >
            {saving ? "Saving…" : "Save"}
          </button>
        </div>
      </div>
      <div className="memory-tabs" aria-label="Memory documents">
        {documents.map((item) => (
          <button
            key={item.id}
            type="button"
            aria-pressed={selected === item.id}
            className={selected === item.id ? "active" : ""}
            onClick={() => setSelected(item.id)}
          >
            {item.name}
          </button>
        ))}
      </div>
      {documentLoading && (
        <div className="settings-empty" role="status">
          Loading {selectedName}…
        </div>
      )}
      {!documentLoading && documentError?.code === "NOT_FOUND" && (
        <div className="settings-empty">
          {selectedName} has not been generated yet.
        </div>
      )}
      {!documentLoading &&
        documentError &&
        documentError.code !== "NOT_FOUND" && (
          <div className="dialog-error" role="alert">
            {documentError.message}
          </div>
        )}
      {!documentLoading && document && (
        <div className="memory-document">
          <div className="memory-document-meta">
            <b>{document.name}</b>
            <span>{formatBytes(document.size)}</span>
            <span>{new Date(document.updatedAt).toLocaleString()}</span>
          </div>
          {document.content ? (
            <div className="memory-document-content">
              <MarkdownContent content={document.content} />
            </div>
          ) : (
            <div className="settings-empty">{document.name} is empty.</div>
          )}
        </div>
      )}
    </section>
  );
}
